CREATE TABLE users(
  id INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(140) NOT NULL,
  password VARCHAR(40) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE categories(
  id INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);
